project:
  type: website
  output-dir: ../docs

website:
  title: "Engage"
  navbar:
    left:
      - text: "explore"
        href: explore.qmd
      - text: "play"
        href: play.qmd
      - text: "learn"
        href: learn.qmd
    right:
      - text: "about"
        href: about.qmd
      - text: "docs"
        href: docs.qmd

format:
  html:
    theme: 
      light: 
        - flatly
        - engage-light.scss
      dark:
        - darkly
        - engage-dark.scss
    css: styles.css



